# Generated by Django 6.0.2 on 2026-02-24 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Peso',
                'verbose_name_plural': 'Registros de Peso',
                'ordering': ['-fecha'],
            },
        ),
    ]
