# Generated by Django 6.0.2 on 2026-02-24 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Rutina', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('es_auto_generada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('equipos', models.ManyToManyField(blank=True, to='exercises.equipo')),
                ('grupos_musculares', models.ManyToManyField(blank=True, to='exercises.grupomuscular')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Entrenamiento', max_length=100)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.rutina')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('series_sugeridas', models.PositiveIntegerField(default=3)),
                ('repeticiones_sugeridas', models.PositiveIntegerField(default=12)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_rutina', to='routines.rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio en Rutina',
                'verbose_name_plural': 'Ejercicios en Rutina',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SerieEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.PositiveIntegerField(default=1)),
                ('repeticiones', models.PositiveIntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, help_text='Peso en kg', null=True)),
                ('peso_corporal', models.FloatField(blank=True, null=True)),
                ('tiempo_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ejercicio')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='routines.entrenamiento')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['ejercicio', 'numero_serie'],
            },
        ),
    ]
