# Generated by Django 6.0.2 on 2026-02-24 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoCaloria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('nivel_actividad', models.CharField(choices=[('sedentario', 'Sedentario (x1.2)'), ('poca', 'Poca actividad (x1.375)'), ('activo', 'Activo (x1.55)'), ('diario', 'Entrena a diario (x1.725)'), ('atleta', 'Atleta (x1.9)')], max_length=20)),
                ('objetivo', models.CharField(choices=[('perder_rapido', 'Perder peso rápido (-1kg/sem)'), ('perder', 'Perder peso (-0.5kg/sem)'), ('mantener', 'Mantener peso'), ('ganar', 'Ganar peso (+0.5kg/sem)'), ('ganar_rapido', 'Ganar peso rápido (+1kg/sem)')], max_length=20)),
                ('tmb', models.FloatField(blank=True, null=True)),
                ('getd', models.FloatField(blank=True, null=True)),
                ('proteinas_g', models.FloatField(blank=True, null=True)),
                ('carbos_g', models.FloatField(blank=True, null=True)),
                ('grasas_g', models.FloatField(blank=True, null=True)),
                ('calculado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cálculo de Calorías',
                'verbose_name_plural': 'Cálculos de Calorías',
            },
        ),
    ]
