# Generated by Django 6.0.2 on 2026-02-24 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('banco', 'Banco'), ('peso_corporal', 'Peso Corporal'), ('disco', 'Disco'), ('mancuernas', 'Mancuernas'), ('barra', 'Barra'), ('barra_dominadas', 'Barra de Dominadas'), ('kettlebell', 'Kettlebell'), ('banda', 'Banda')], max_length=50, unique=True)),
                ('icono', models.CharField(blank=True, default='🏋️', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Grupo Muscular',
                'verbose_name_plural': 'Grupos Musculares',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
                ('gif', models.FileField(blank=True, null=True, upload_to='ejercicios/gifs/')),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipos', models.ManyToManyField(blank=True, related_name='ejercicios', to='exercises.equipo')),
                ('grupo_muscular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios', to='exercises.grupomuscular')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['nombre'],
            },
        ),
    ]
